[main]
entrypoints = ["./src/extension.ts"]
outdir = "./dist"
sourcemap = "external"
external = ["vscode"]

[target.node]
format = "cjs"
minify = false

[resolve]
# Use "module" field before "main"
mainFields = ["module", "main"]